name: Deploy Backend to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # AdoptOpenJDK is now Eclipse Temurin
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 49.13.170.189 >> ~/.ssh/known_hosts
    - name: Stop existing container
      run: ssh root@49.13.170.189 "docker stop apoint-backend-new"

    - name: Remove existing container
      run: ssh root@49.13.170.189 "docker rm apoint-backend-new"

    - name: Remove existing image
      run: ssh root@49.13.170.189 "docker rmi apoint-backend-new"

    - name: Remove existing files
      run: ssh root@49.13.170.189 "rm -rf /var/www/myapp/backend"

    - name: Create new backend folder
      run: ssh root@49.13.170.189 "mkdir /var/www/myapp/backend"
      
    - name: Transfer files
      run: |
        scp -r target Dockerfile root@49.13.170.189:/var/www/myapp/backend
    - name: Build the Docker image
      run: ssh root@49.13.170.189 "cd /var/www/myapp/backend && docker build -t apoint-backend-new:latest ."

    - name: Run the Docker container
      run: |
        ssh root@49.13.170.189 "docker run -d --name apoint-backend-new --network apoint -p 8081:8081 \
        -e APP_CORS_ALLOWEDORIGINS='${{ APP_CORS_ALLOWEDORIGINS }}' \
        -e SERVER_PORT='${{ secrets.SERVER_PORT }}' \
        -e APP_URL='${{ secrets.APP_URL }}' \
        -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
        -e SPRING_DATASOURCE_URL='${{ secrets.SPRING_DATASOURCE_URL }}' \
        -e SPRING_DATASOURCE_USERNAME='${{ secrets.SPRING_DATASOURCE_USERNAME }}' \
        -e SPRING_DATASOURCE_PASSWORD='${{ secrets.SPRING_DATASOURCE_PASSWORD }}' \
        -e GOOGLE_API_KEY='${{ secrets.GOOGLE_API_KEY }}' \
        -e SPRING_MAIL_HOST='${{ secrets.SPRING_MAIL_HOST }}' \
        -e SPRING_MAIL_PORT='${{ secrets.SPRING_MAIL_PORT }}' \
        -e SPRING_MAIL_USERNAME='${{ secrets.SPRING_MAIL_USERNAME }}' \
        -e SPRING_MAIL_PASSWORD='${{ secrets.SPRING_MAIL_PASSWORD }}' \
        -e SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST='${{ secrets.SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST }}' \
        apoint-backend-new:latest"

